//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSR.Models.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accomplishment
    {
        public int ActivityId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string Activity { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string AddedBy { get; set; }
    }
}
