//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSR.Models.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSRMaster
    {
        public int DSRId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string CurrentPhase { get; set; }
        public Nullable<System.DateTime> DSRDate { get; set; }
        public string Status { get; set; }
        public string SentBy { get; set; }
        public Nullable<int> Issue { get; set; }
        public Nullable<int> Risk { get; set; }
        public Nullable<int> OpenItem { get; set; }
    }
}
