//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSR.Models.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public Nullable<System.DateTime> PlnSrtDate { get; set; }
        public Nullable<System.DateTime> ActSrtDate { get; set; }
        public Nullable<System.DateTime> PlnEndDate { get; set; }
        public Nullable<System.DateTime> ActEndDate { get; set; }
        public string ProjectDL { get; set; }
        public string PM { get; set; }
        public Nullable<System.DateTime> LastDSR { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
